package com.investec.expd.model;
// Generated 02 Dec 2016 9:27:23 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Ideaskills generated by hbm2java
 */
@Entity
@Table(name = "ideaskills")
@NamedQueries({ 
	@NamedQuery(name = "ideaskills.FindBySkillID", query = "select u from Ideaskills u where u.ideaSkillsId=:ideaSkillsId"),
	})
public class Ideaskills implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1118002098462839595L;
	private int ideaSkillsId;
	private Idea idea;
	private Skills skills;

	public Ideaskills() {
	}

	public Ideaskills(int ideaSkillsId, Idea idea, Skills skills) {
		this.ideaSkillsId = ideaSkillsId;
		this.idea = idea;
		this.skills = skills;
	}

	@Id

	@Column(name = "IdeaSkillsID", unique = true, nullable = false)
	public int getIdeaSkillsId() {
		return this.ideaSkillsId;
	}

	public void setIdeaSkillsId(int ideaSkillsId) {
		this.ideaSkillsId = ideaSkillsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdeaID", nullable = false)
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SkillsID", nullable = false)
	public Skills getSkills() {
		return this.skills;
	}

	public void setSkills(Skills skills) {
		this.skills = skills;
	}

}
