package com.investec.expd.model;
// Generated 02 Dec 2016 9:27:23 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Notes generated by hbm2java
 */
@Entity
@Table(name = "notes")
@NamedQueries({ 
	@NamedQuery(name = "note.FindByNoteID", query = "select u from Notes u where u.notesId=:notesId"),
	})
public class Notes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2404822615579905823L;
	private int notesId;
	private Idea idea;
	private User user;
	private String text;

	public Notes() {
	}

	public Notes(int notesId, Idea idea, User user) {
		this.notesId = notesId;
		this.idea = idea;
		this.user = user;
	}

	public Notes(int notesId, Idea idea, User user, String text) {
		this.notesId = notesId;
		this.idea = idea;
		this.user = user;
		this.text = text;
	}

	@Id

	@Column(name = "NotesID", unique = true, nullable = false)
	public int getNotesId() {
		return this.notesId;
	}

	public void setNotesId(int notesId) {
		this.notesId = notesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdeaID", nullable = false)
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "Text", length = 2000)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
