package com.investec.expd.model;
// Generated 02 Dec 2016 9:27:23 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Skills generated by hbm2java
 */
@Entity
@Table(name = "skills")
public class Skills implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8863695171444990649L;
	private int skillsId;
	private String name;
	private String description;
	private Set<Ideaskills> ideaskillses = new HashSet<Ideaskills>(0);
	private Set<Userskills> userskillses = new HashSet<Userskills>(0);

	public Skills() {
	}

	public Skills(int skillsId, String name) {
		this.skillsId = skillsId;
		this.name = name;
	}

	public Skills(int skillsId, String name, String description, Set<Ideaskills> ideaskillses,
			Set<Userskills> userskillses) {
		this.skillsId = skillsId;
		this.name = name;
		this.description = description;
		this.ideaskillses = ideaskillses;
		this.userskillses = userskillses;
	}

	@Id

	@Column(name = "SkillsID", unique = true, nullable = false)
	public int getSkillsId() {
		return this.skillsId;
	}

	public void setSkillsId(int skillsId) {
		this.skillsId = skillsId;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skills")
	public Set<Ideaskills> getIdeaskillses() {
		return this.ideaskillses;
	}

	public void setIdeaskillses(Set<Ideaskills> ideaskillses) {
		this.ideaskillses = ideaskillses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skills")
	public Set<Userskills> getUserskillses() {
		return this.userskillses;
	}

	public void setUserskillses(Set<Userskills> userskillses) {
		this.userskillses = userskillses;
	}

}
