package com.investec.expd.model;
// Generated 02 Dec 2016 9:27:23 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tasks generated by hbm2java
 */
@Entity
@Table(name = "tasks")
@NamedQueries({ 
	@NamedQuery(name = "tasks.FindByTaskID", query = "select u from Tasks u where u.taskId=:taskId"),
	})
public class Tasks implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2634148332648793772L;
	private int taskId;
	private Idea idea;
	private String taskName;
	private double percentageComplete;
	private BigDecimal value;
	private Date dueDate;
	private Set<Mappings> mappingses = new HashSet<Mappings>(0);

	public Tasks() {
	}

	public Tasks(int taskId, double percentageComplete) {
		this.taskId = taskId;
		this.percentageComplete = percentageComplete;
	}

	public Tasks(int taskId, Idea idea, String taskName, double percentageComplete, BigDecimal value, Date dueDate,
			Set<Mappings> mappingses) {
		this.taskId = taskId;
		this.idea = idea;
		this.taskName = taskName;
		this.percentageComplete = percentageComplete;
		this.value = value;
		this.dueDate = dueDate;
		this.mappingses = mappingses;
	}

	@Id

	@Column(name = "TaskID", unique = true, nullable = false)
	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdeaID")
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@Column(name = "TaskName", length = 100)
	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	@Column(name = "PercentageComplete", nullable = false, precision = 22, scale = 0)
	public double getPercentageComplete() {
		return this.percentageComplete;
	}

	public void setPercentageComplete(double percentageComplete) {
		this.percentageComplete = percentageComplete;
	}

	@Column(name = "Value", scale = 4)
	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DueDate", length = 19)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tasks")
	public Set<Mappings> getMappingses() {
		return this.mappingses;
	}

	public void setMappingses(Set<Mappings> mappingses) {
		this.mappingses = mappingses;
	}

}
