package com.investec.expd.model;
// Generated 02 Dec 2016 9:27:23 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userskills generated by hbm2java
 */
@Entity
@Table(name = "userskills")
public class Userskills implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5568651244144468463L;
	private int userSkillsId;
	private Skills skills;
	private User user;

	public Userskills() {
	}

	public Userskills(int userSkillsId, Skills skills, User user) {
		this.userSkillsId = userSkillsId;
		this.skills = skills;
		this.user = user;
	}

	@Id

	@Column(name = "UserSkillsID", unique = true, nullable = false)
	public int getUserSkillsId() {
		return this.userSkillsId;
	}

	public void setUserSkillsId(int userSkillsId) {
		this.userSkillsId = userSkillsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SkillsID", nullable = false)
	public Skills getSkills() {
		return this.skills;
	}

	public void setSkills(Skills skills) {
		this.skills = skills;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
